# Generated by Django 4.1.7 on 2023-03-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='idcategoriacatalogo',
            field=models.ForeignKey(blank=True, db_column='idcategoriacatalogo', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datosmaestros.catcategoriacatalogo'),
        ),
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='iddependencia',
            field=models.ForeignKey(blank=True, db_column='iddependencia', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datosmaestros.catdependencia'),
        ),
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='idnivelconfidencialidad',
            field=models.ForeignKey(blank=True, db_column='idnivelconfidencialidad', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datosmaestros.catnivelconfidencialidad'),
        ),
    ]
