# Generated by Django 4.1.7 on 2023-07-18 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datosmaestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcatnivelconfidencialidad',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcatdependencia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcatcategoriacatalogo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcatcatalogo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcatcatalogo',
            name='idcategoriacatalogo',
            field=models.ForeignKey(blank=True, db_column='idcategoriacatalogo', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datosmaestros.catcategoriacatalogo'),
        ),
        migrations.AddField(
            model_name='historicalcatcatalogo',
            name='iddependencia',
            field=models.ForeignKey(blank=True, db_column='iddependencia', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datosmaestros.catdependencia'),
        ),
        migrations.AddField(
            model_name='historicalcatcatalogo',
            name='idnivelconfidencialidad',
            field=models.ForeignKey(blank=True, db_column='idnivelconfidencialidad', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datosmaestros.catnivelconfidencialidad'),
        ),
        migrations.AddField(
            model_name='catcatalogo',
            name='idcategoriacatalogo',
            field=models.ForeignKey(db_column='idcategoriacatalogo', on_delete=django.db.models.deletion.DO_NOTHING, to='datosmaestros.catcategoriacatalogo'),
        ),
        migrations.AddField(
            model_name='catcatalogo',
            name='iddependencia',
            field=models.ForeignKey(db_column='iddependencia', on_delete=django.db.models.deletion.DO_NOTHING, to='datosmaestros.catdependencia'),
        ),
        migrations.AddField(
            model_name='catcatalogo',
            name='idnivelconfidencialidad',
            field=models.ForeignKey(db_column='idnivelconfidencialidad', on_delete=django.db.models.deletion.DO_NOTHING, to='datosmaestros.catnivelconfidencialidad'),
        ),
    ]
