# Generated by Django 4.1.7 on 2023-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcategoriacatalogo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='catcategoriacatalogo',
            name='deleted_at',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AlterField(
            model_name='catcategoriacatalogo',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', null=True),
        ),
        migrations.AlterField(
            model_name='catcategoriacatalogo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='catcategoriacatalogo',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', null=True),
        ),
        migrations.AlterField(
            model_name='catdependencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='catdependencia',
            name='deleted_at',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AlterField(
            model_name='catdependencia',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', null=True),
        ),
        migrations.AlterField(
            model_name='catdependencia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='catdependencia',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', null=True),
        ),
        migrations.AlterField(
            model_name='catnivelconfidencialidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='catnivelconfidencialidad',
            name='deleted_at',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AlterField(
            model_name='catnivelconfidencialidad',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', null=True),
        ),
        migrations.AlterField(
            model_name='catnivelconfidencialidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='catnivelconfidencialidad',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatcategoriacatalogo',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcatcategoriacatalogo',
            name='deleted_at',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatcategoriacatalogo',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatcategoriacatalogo',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='updated_at', editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcatcategoriacatalogo',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatdependencia',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcatdependencia',
            name='deleted_at',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatdependencia',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatdependencia',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='updated_at', editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcatdependencia',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatnivelconfidencialidad',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcatnivelconfidencialidad',
            name='deleted_at',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatnivelconfidencialidad',
            name='deleted_by',
            field=models.IntegerField(db_column='deleted_by', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatnivelconfidencialidad',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='updated_at', editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcatnivelconfidencialidad',
            name='updated_by',
            field=models.IntegerField(db_column='updated_by', null=True),
        ),
    ]
