# Generated by Django 4.1.7 on 2023-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0003_alter_historicalcatcatalogo_idcatalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='idcatalogo',
            field=models.IntegerField(auto_created=True, db_column='idCatalogo', db_index=True, verbose_name='ID'),
        ),
    ]
