# Generated by Django 4.1.7 on 2023-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0003_alter_catcategoriacatalogo_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcatcategoriacatalogo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcatdependencia',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcatnivelconfidencialidad',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='catcategoriacatalogo',
            name='esactivo',
        ),
        migrations.RemoveField(
            model_name='catdependencia',
            name='esactivo',
        ),
        migrations.RemoveField(
            model_name='catnivelconfidencialidad',
            name='esactivo',
        ),
        migrations.AddField(
            model_name='catcategoriacatalogo',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AddField(
            model_name='catdependencia',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AddField(
            model_name='catnivelconfidencialidad',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.DeleteModel(
            name='HistoricalCatCatalogo',
        ),
        migrations.DeleteModel(
            name='HistoricalCatCategoriaCatalogo',
        ),
        migrations.DeleteModel(
            name='HistoricalCatDependencia',
        ),
        migrations.DeleteModel(
            name='HistoricalCatNivelConfidencialidad',
        ),
    ]
