# Generated by Django 4.1.7 on 2023-07-18 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datosmaestros', '0004_remove_historicalcatcategoriacatalogo_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcatalogo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
