# Generated by Django 4.1.7 on 2023-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0004_alter_historicalcatcatalogo_idcatalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='idcatalogo',
            field=models.IntegerField(blank=True, db_column='idCatalogo', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcatcategoriacatalogo',
            name='idcategoriacatalogo',
            field=models.IntegerField(blank=True, db_column='idCategoriaCatalogo', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcatdependencia',
            name='iddependencia',
            field=models.IntegerField(blank=True, db_column='idDependencia', db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcatnivelconfidencialidad',
            name='idnivelconfidencialidad',
            field=models.IntegerField(blank=True, db_column='idNivelConfidencialidad', db_index=True),
        ),
    ]
