# Generated by Django 4.1.7 on 2023-03-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0005_alter_historicalcatcatalogo_idcatalogo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcatalogo',
            options={'verbose_name': 'Catalogos', 'verbose_name_plural': 'Catalogos'},
        ),
    ]
