# Generated by Django 4.1.7 on 2023-07-18 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datosmaestros', '0005_catcatalogo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catcatalogo',
            name='user',
        ),
        migrations.CreateModel(
            name='PermisosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_by', models.IntegerField(db_column='created_by')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('updated_by', models.IntegerField(db_column='updated_by', null=True)),
                ('deleted_at', models.DateTimeField(db_column='deleted_at', null=True)),
                ('deleted_by', models.IntegerField(db_column='deleted_by', null=True)),
                ('permiso_lectura', models.BooleanField(default=True)),
                ('permiso_escritura', models.BooleanField(default=True)),
                ('permiso_eliminacion', models.BooleanField(default=True)),
                ('permiso_actualizacion', models.BooleanField(default=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosmaestros.catcatalogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
