# Generated by Django 4.1.7 on 2023-03-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0006_alter_catcatalogo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcatalogo',
            options={'managed': False, 'verbose_name': 'Catalogos', 'verbose_name_plural': 'Catalogos'},
        ),
    ]
