# Generated by Django 4.1.7 on 2023-03-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaestros', '0008_alter_historicalcatcatalogo_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcatcatalogo',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='deleted_by',
            field=models.IntegerField(blank=True, db_column='deleted_by', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatcatalogo',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='updated_by', null=True),
        ),
    ]
